name: Remove

on:
  workflow_dispatch:
  #schedule:
  # - cron: '0 20 * * 1'

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-22.04
    steps:
    - name: 删除任务
      uses: FunctionXJB/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
